### ISSUE TITLE
Presample generator function for case: stacking presamples/inheritance

### ISSUE THREAD

**Issue by cmutel** [PascalLesage/brightway2-presamples#12]
As a means to account for design iterations with underspecified models

**Comment by cmutel** [comment]
@PascalLesage I am tempted to give this milestone 1.5, as well as campaign inheritance in general - it would be nice to get a 1.0 out the door.

**Comment by PascalLesage** [comment]
[This](https://github.com/PascalLesage/brightway2-presamples/blob/master/bw_presamples/campaigns.py) already works.

**Comment by cmutel** [comment]
Sure, but I guess we need tests, and also for each of these a real case study in the documentation (i.e. a notebook).

**Comment by PascalLesage** [comment]
Docs to Notebook shows this working.

**Comment by cmutel** [comment]
This works, and is included in tests and doc notebook
