### ISSUE TITLE
Presample generator function for case: select one input at a time

### ISSUE THREAD

**Issue by cmutel** [PascalLesage/brightway2-presamples#13]
Should also have a real example

**Comment by PascalLesage** [comment]
[This](https://github.com/PascalLesage/brightway2-presamples/blob/master/bw_presamples/utils.py#L127) works. 
Is the request for a presamples package to be created directly, instead of first generating the samples and then creating the presamples package?

**Comment by PascalLesage** [comment]
Done: https://github.com/PascalLesage/brightway2-presamples/blob/master/bw_presamples/models/kronecker_delta.py
