### ISSUE TITLE
Inconsistent arguments for RPA instantiation

### ISSUE THREAD

**Issue by PascalLesage** [PascalLesage/brightway2-presamples#31]
Places that assume list of (fp, shape):
https://github.com/PascalLesage/brightway2-presamples/blob/seed/presamples/array.py#L20
https://github.com/PascalLesage/brightway2-presamples/blob/seed/presamples/array.py#L11

Places that assume list of fps only:
https://github.com/PascalLesage/brightway2-presamples/blob/seed/presamples/loader.py#L176
https://github.com/PascalLesage/brightway2-presamples/blob/seed/presamples/package_interface.py#L113

TODO: confirm that list of (fp, shape) is what is required, and revert RPA instantiations to pass (fp, shape).

**Comment by cmutel** [comment]
Fixed in d9613f5.
