### ISSUE TITLE
hash should be for data, not data location

### ISSUE THREAD

**Issue by PascalLesage** [PascalLesage/brightway2-presamples#9]
The hash included in the presamples package is for the location of the data on disk. We eventually want to have data stored off-disk (see https://github.com/PascalLesage/brightway2-presamples/issues/7).  
Since what we want to ensure is that the actual *data* passed is not corrupt, it would be preferable to hash the data (samples, parameter names, etc).

**Comment by cmutel** [comment]
Not sure why youthink we hash the location and not the actual contents - we import `bw2data.filesystem.md5`, which is definitely [hashing the file content](https://bitbucket.org/cmutel/brightway2-data/src/8970cf8736cb3e22338a9f4760c9995cd6979a40/bw2data/filesystem.py?at=default&fileviewer=file-view-default#filesystem.py-48).

I agree that this whole system should be redesigned to account for remote resources where we don't have access to the filesystem, and can't check the contents. But I think this discussion should be postponed for now.

**Comment by PascalLesage** [comment]
Because the datapackage `hash` fontains the hash of the filepaths, see e.g. [here](https://github.com/PascalLesage/brightway2-presamples/blob/master/bw_presamples/create_presamples_package.py#L157) is what is stored as a hash:
`"hash": md5(cfs_samples_fp)`
